#!/usr/bin/python3 
graph_1 = {
    "Addis Ababa": [("Ambo", 4), ("Adama", 3), ("Debre Berhan", 5), ("Holeta", 1)],
    "Ambo": [("Addis Ababa", 4), ("Woliso", 3)],
    "Adama": [("Addis Ababa", 3), ("Assella", 4), ("Batu", 3)],
    "Debre Berhan": [("Addis Ababa", 5), ("Debre Sina", 3)],
    "Holeta": [("Addis Ababa", 1)],
    "Woliso": [("Ambo", 3), ("Jimma", 6)],
    "Jimma": [("Woliso", 6), ("Bonga", 4)],
    "Bonga": [("Jimma", 4), ("Gore", 5)],
    "Gore": [("Bonga", 5), ("Gambela", 6)],
    "Gambela": [("Gore", 6)],
    "Assella": [("Adama", 4), ("Dodola", 3)],
    "Dodola": [("Assella", 3), ("Bale", 4)],
    "Bale": [("Dodola", 4), ("Goba", 6)],
    "Goba": [("Bale", 6), ("Liben", 13)],
    "Liben": [("Goba", 13), ("Moyale", 11)],
    "Moyale": [("Liben", 11)],
    "Batu": [("Adama", 3), ("Shashemene", 4), ("Arsi Negele", 3)],
    "Shashemene": [("Batu", 4), ("Awasa", 3)],
    "Awasa": [("Shashemene", 3), ("Dilla", 4)],
    "Dilla": [("Awasa", 4), ("Yabelo", 6)],
    "Yabelo": [("Dilla", 6), ("Konso", 3)],
    "Konso": [("Yabelo", 3), ("Arba Minch", 6)],
    "Arba Minch": [("Konso", 6)],
    "Debre Sina": [("Debre Berhan", 3), ("Kemise", 4)],
    "Kemise": [("Debre Sina", 4), ("Dessie", 3)],
    "Dessie": [("Kemise", 3), ("Woldia", 4)],
    "Woldia": [("Dessie", 4), ("Lalibela", 11)],
    "Lalibela": [("Woldia", 11), ("Sekota", 8)],
    "Sekota": [("Lalibela", 8), ("Axum", 6)],
    "Axum": [("Sekota", 6), ("Shire", 8)],
    "Shire": [("Axum", 8), ("Humera", 7)],
    "Humera": [("Shire", 7), ("Kartu", 21)],
    "Kartu": [("Humera", 21)]
}
graph_2= {
    'Addis Ababa': ['Ambo', 'Adama', 'Debre Berhan', 'Holeta'],
    'Ambo': ['Addis Ababa', 'Woliso'],
    'Adama': ['Addis Ababa', 'Assella', 'Batu'],
    'Debre Berhan': ['Addis Ababa', 'Debre Sina'],
    'Holeta': ['Addis Ababa'],
    'Woliso': ['Ambo', 'Jimma'],
    'Jimma': ['Woliso', 'Bonga'],
    'Bonga': ['Jimma', 'Gore'],
    'Gore': ['Bonga', 'Gambela'],
    'Gambela': ['Gore'],
    'Assella': ['Adama', 'Dodola'],
    'Dodola': ['Assella', 'Bale'],
    'Bale': ['Dodola', 'Goba'],
    'Goba': ['Bale', 'Liben'],
    'Liben': ['Goba', 'Moyale'],
    'Moyale': ['Liben'],
    'Batu': ['Adama', 'Shashemene', 'Arsi Negele'],
    'Shashemene': ['Batu', 'Awasa'],
    'Awasa': ['Shashemene', 'Dilla'],
    'Dilla': ['Awasa', 'Yabelo'],
    'Yabelo': ['Dilla', 'Konso'],
    'Konso': ['Yabelo', 'Arba Minch'],
    'Arba Minch': ['Konso'],
    'Debre Sina': ['Debre Berhan', 'Kemise'],
    'Kemise': ['Debre Sina', 'Dessie'],
    'Dessie': ['Kemise', 'Woldia'],
    'Woldia': ['Dessie', 'Lalibela'],
    'Lalibela': ['Woldia', 'Sekota'],
    'Sekota': ['Lalibela', 'Axum'],
    'Axum': ['Sekota', 'Shire'],
    'Shire': ['Axum', 'Humera'],
    'Humera': ['Shire', 'Kartu'],
    'Kartu': ['Humera'],
}
print(f"length of graph 1: {len(graph_1)}")
print(f"length of graph 2: {len(graph_2)}")