traveling_sales_man = {
    "Addis Ababa": {
        "Mekelle": {"distance": 447, "heuristic": 400},
        "Hawassa": {"distance": 533, "heuristic": 250},
        "Dire Dawa": {"distance": 380, "heuristic": 200},
        "Bahir Dar": {"distance": 225, "heuristic": 150},
        "Jimma": {"distance": 230, "heuristic": 100},
        "Gondar": {"distance": 166, "heuristic": 140},
        "Adama": {"distance": 598, "heuristic": 50},
        "Debre Berhan": {"distance": 276, "heuristic": 80},
        "Harar": {"distance": 201, "heuristic": 180},
    },
    "Mekelle": {
        "Addis Ababa": {"distance": 447, "heuristic": 400},
        "Hawassa": {"distance": 331, "heuristic": 550},
        "Dire Dawa": {"distance": 394, "heuristic": 250},
        "Bahir Dar": {"distance": 644, "heuristic": 300},
        "Jimma": {"distance": 329, "heuristic": 500},
        "Gondar": {"distance": 273, "heuristic": 280},
        "Adama": {"distance": 150, "heuristic": 350},
        "Debre Berhan": {"distance": 161, "heuristic": 380},
        "Harar": {"distance": 426, "heuristic": 500},
    },
    "Hawassa": {
        "Addis Ababa": {"distance": 533, "heuristic": 250},
        "Mekelle": {"distance": 331, "heuristic": 550},
        "Dire Dawa": {"distance": 569, "heuristic": 300},
        "Bahir Dar": {"distance": 682, "heuristic": 500},
        "Jimma": {"distance": 250, "heuristic": 200},
        "Gondar": {"distance": 396, "heuristic": 400},
        "Adama": {"distance": 164, "heuristic": 150},
        "Debre Berhan": {"distance": 275, "heuristic": 300},
        "Harar": {"distance": 546, "heuristic": 350},
    },
    "Dire Dawa": {
        "Addis Ababa": {"distance": 380, "heuristic": 200},
        "Mekelle": {"distance": 394, "heuristic": 250},
        "Hawassa": {"distance": 569, "heuristic": 300},
        "Bahir Dar": {"distance": 430, "heuristic": 400},
        "Jimma": {"distance": 615, "heuristic": 500},
        "Gondar": {"distance": 344, "heuristic": 350},
        "Adama": {"distance": 477, "heuristic": 150},
        "Debre Berhan": {"distance": 424, "heuristic": 200},
        "Harar": {"distance": 123, "heuristic": 50},
    },
    "Bahir Dar": {
        "Addis Ababa": {"distance": 225, "heuristic": 150},
        "Mekelle": {"distance": 644, "heuristic": 300},
        "Hawassa": {"distance": 682, "heuristic": 500},
        "Dire Dawa": {"distance": 430, "heuristic": 400},
        "Jimma": {"distance": 405, "heuristic": 300},
        "Gondar": {"distance": 378, "heuristic": 350},
        "Adama": {"distance": 729, "heuristic": 400},
        "Debre Berhan": {"distance": 482, "heuristic": 200},
        "Harar": {"distance": 197, "heuristic": 180},
    },
    "Jimma": {
        "Addis Ababa": {"distance": 230, "heuristic": 100},
        "Mekelle": {"distance": 329, "heuristic": 500},
        "Hawassa": {"distance": 250, "heuristic": 200},
        "Dire Dawa": {"distance": 615, "heuristic": 500},
        "Bahir Dar": {"distance": 405, "heuristic": 300},
        "Gondar": {"distance": 227, "heuristic": 200},
        "Adama": {"distance": 422, "heuristic": 150},
        "Debre Berhan": {"distance": 223, "heuristic": 100},
        "Harar": {"distance": 400, "heuristic": 300},
    },
    "Gondar": {
        "Addis Ababa": {"distance": 166, "heuristic": 140},
        "Mekelle": {"distance": 273, "heuristic": 280},
        "Hawassa": {"distance": 396, "heuristic": 400},
        "Dire Dawa": {"distance": 344, "heuristic": 350},
        "Bahir Dar": {"distance": 378, "heuristic": 350},
        "Jimma": {"distance": 227, "heuristic": 200},
        "Adama": {"distance": 329, "heuristic": 150},
        "Debre Berhan": {"distance": 142, "heuristic": 80},
        "Harar": {"distance": 206, "heuristic": 180},
    },
    "Adama": {
        "Addis Ababa": {"distance": 598, "heuristic": 50},
        "Mekelle": {"distance": 150, "heuristic": 350},
        "Hawassa": {"distance": 164, "heuristic": 150},
        "Dire Dawa": {"distance": 477, "heuristic": 150},
        "Bahir Dar": {"distance": 729, "heuristic": 400},
        "Jimma": {"distance": 422, "heuristic": 150},
        "Gondar": {"distance": 329, "heuristic": 150},
        "Debre Berhan": {"distance": 280, "heuristic": 80},
        "Harar": {"distance": 546, "heuristic": 180},
    },
    "Debre Berhan": {
        "Addis Ababa": {"distance": 276, "heuristic": 80},
        "Mekelle": {"distance": 161, "heuristic": 380},
        "Hawassa": {"distance": 275, "heuristic": 300},
        "Dire Dawa": {"distance": 424, "heuristic": 200},
        "Bahir Dar": {"distance": 482, "heuristic": 200},
        "Jimma": {"distance": 223, "heuristic": 100},
        "Gondar": {"distance": 142, "heuristic": 80},
        "Adama": {"distance": 280, "heuristic": 80},
        "Harar": {"distance": 282, "heuristic": 180},
    },
    "Harar": {
        "Addis Ababa": {"distance": 201, "heuristic": 180},
        "Mekelle": {"distance": 426, "heuristic": 500},
        "Hawassa": {"distance": 546, "heuristic": 350},
        "Dire Dawa": {"distance": 123, "heuristic": 50},
        "Bahir Dar": {"distance": 197, "heuristic": 180},
        "Jimma": {"distance": 400, "heuristic": 300},
        "Gondar": {"distance": 206, "heuristic": 180},
        "Adama": {"distance": 546, "heuristic": 180},
        "Debre Berhan": {"distance": 282, "heuristic": 180},
    },
}

